- name: "OMF | Ensure Fish is installed"
  shell: command -v fish
  register: fish_result
  tags:
    - always
    - omf
    - omf_install

- name: "OMF | Check if OMF is installed"
  shell: fish -c "omf --version"
  register: result
  changed_when: false
  tags:
    - always
    - omf
    - omf_install

- set_fact:
    fish_installed: "{{ not fish_result.failed | bool }}"
    omf_installed: "{{ not result.failed | bool }}"
  tags:
    - always
    - omf

- name: "OMF | Install OMF"
  when: (fish_installed == true) and (omf_installed == false)
  shell: curl -L https://get.oh-my.fish | fish --init-command 'set argv -- --noninteractive'
  tags:
    - always
    - omf
    - omf_install

