---
- name: "Fish | Install Fish and Fisher"
  community.general.homebrew:
    name:
      - fish
      - fisher
    state: present
  tags:
    - always
    - homebrew
    - homebrew_install
    - fish
    - fisher

- name: "Fish | Copy Fish Plugins"
  ansible.builtin.copy:
    src: files/fish_plugins
    dest: ~/.config/fish/fish_plugins
  tags:
    - fish
    - fisher
    - fisher_install

- name: "Fish | Copy Functions"
  copy:
    src: files/functions/
    dest: ~/.config/fish/functions/

- name: "Fish | Install Fish Plugins"
  ansible.builtin.shell: fish -c "fisher update"
  tags:
    - fish
    - fisher
    - fisher_install
