name: dotfiles
root: ~/

windows:
  - dotfiles:
      root: ~/.dotfiles
      layout: main-vertical
      panes:
        - files:
            - clear; neofetch
            - ll
        - editor:
            - nvim
  - dotconfig:
      root: ~/.config
      layout: main-vertical
      panes:
        - files:
            - clear; neofetch
        - editor:
            - clear
            - ll
  - system-monitor:
      layout: even-horizontal
      panes:
        - ping:
            - clear
            - prettyping www.google.com
        - btop:
            - btop
