name: abiyasa-dev
root: ~/abiyasa-dev/

windows:
  - abiyasa-dev:
      layout: main-vertical
      panes:
        - files:
            - clear; neofetch
        - editor:
            - clear
            - ll
