---
- name: "Ensure VirtualEnv is installed"
  homebrew:
    name: virtualenv
    state: present
  tags:
    - cron

- name: "Scripts | Ensure ~/.scripts folder exists"
  file:
    path: ~/.scripts
    state: directory
  tags:
    - cron

- name: "Setup NH Organizer"
  vars:
    current_install_dir: "~/.scripts/nh-organizer"
    repository: "{{ nho.repository }}"
  block:
    - name: "NHO | Clone from repository"
      git:
        repo: "{{ repository }}"
        dest: "{{ current_install_dir }}"
        update: yes
        force: yes
    - name: "NHO | Write .env file"
      copy:
        dest: "{{ current_install_dir }}/.env"
        content: "{{ nho.env }}"
    - name: "NHO | Install requirements"
      pip:
        requirements: "{{ current_install_dir }}/requirements.txt"
        virtualenv: "{{ current_install_dir }}/.venv"
    - name: "NHO | Run zip_to_cbz.py every hour at 0 minutes"
      cron:
        name: "NHO-cbz"
        minute: "0"
        hour: "*"
        job: "cd {{ current_install_dir }} && PYTHON_ENV=production .venv/bin/python zip_to_cbz.py --path=/Volumes/Seagate2TB/done"
    - name: "NHO | Run to_temporarily.py every hour at 30 minutes"
      cron:
        name: "NHO-temporarily"
        minute: "30"
        hour: "*"
        job: "cd {{ current_install_dir }} && PYTHON_ENV=production .venv/bin/python to_temporarily.py --from=/Volumes/Seagate2TB/done"
  tags:
    - cron

- name: "H3D Organizer"
  vars:
    current_install_dir: "~/.scripts/h3d-organizer"
    repository: "{{ h3d.repository }}"
  block:
    - name: "H3D | Clone from repository"
      git:
        repo: "{{ repository }}"
        dest: "{{ current_install_dir }}"
        update: yes
        force: yes
    - name: "H3D | Write .env file"
      copy:
        dest: "{{ current_install_dir }}/.env"
        content: "{{ h3d.env }}"
    - name: "H3D | Install requirements"
      pip:
        requirements: "{{ current_install_dir }}/requirements.txt"
        virtualenv: "{{ current_install_dir }}/.venv"
    - name: "H3D | Run unzip.py every hour at 15 minutes"
      cron:
        name: "H3D-unzip"
        minute: "0"
        hour: "*"
        job: "cd {{ current_install_dir }} && PYTHON_ENV=production .venv/bin/python unzip.py --path='/Volumes/Seagate2TB/JDownloader/Various Files/' --use-version=3"
    - name: "H3D | Run transcode every hour at 45 minutes"
      cron:
        name: "H3D-transcode"
        minute: "10,30,50"
        hour: "*"
        job: "cd {{ current_install_dir }} && PATH=/opt/homebrew/bin:${PATH} PYTHON_ENV=production .venv/bin/python transcode.py --path=/Volumes/Seagate2TB/H3D/ --max=0 --max-bytes=0G --max-time=15m --use-version=3"
    - name: "H3D | Run gallery every hour at 30 minutes"
      cron:
        name: "H3D-gallery"
        minute: "15,45"
        hour: "*"
        job: "cd {{ current_install_dir }} && PYTHON_ENV=production .venv/bin/python gallery.py --path=/Volumes/Seagate2TB/H3D/ --max-bytes=512M --max-time=15m"
  tags:
    - cron
