---
- name: "Cron | Brew update every day at 12 noon"
  cron:
    name: "Brew Update"
    minute: "0"
    hour: "12"
    job: "brew update"
  tags: 
    - cron
    - brew
    - brew_update

- name: "Cron | Brew cleanup every 1st of the month at 12:30 noon"
  cron:
    name: "Brew Cleanup"
    minute: "30"
    hour: "12"
    day: "1"
    job: "brew cleanup --prune=all"
  tags: 
    - cron
    - brew
    - brew_cleanup

- name: "Cron | Ensure VirtualEnv is installed"
  homebrew:
    name: virtualenv
    state: present
  tags: 
    - cron

- name: "Cron | Setup Automate.py"
  block:
    - name: "Automate | Ensure ~/.scripts/automate folder exists"
      file:
        path: ~/.scripts/automate
        state: directory
    - name: "H3D | Copy scripts"
      copy:
        src: scripts/automate/{{ item }}
        dest: ~/.scripts/automate/{{ item }}
      loop:
        - automate.py
        - requirements.txt
    - name: "H3D | Install requirements"
      pip:
        requirements: ~/.scripts/automate/requirements.txt
        virtualenv: ~/.scripts/automate
    - name: "Automate | Run automate.py to run every hour"
      cron:
        name: "Automate"
        minute: "0"
        hour: "*"
        job: "~/.scripts/automate/bin/python3 ~/.scripts/automate/automate.py"
  tags:
      - cron

- name: "Cron | H3D"
  block:
    - name: "H3D | Ensure ~/.scripts/h3d folder exists"
      file:
        path: ~/.scripts/h3d
        state: directory
    - name: "H3D | Copy scripts"
      copy:
        src: scripts/h3d/{{ item }}
        dest: ~/.scripts/h3d/{{ item }}
      loop:
        - h3d.py
        - h3d_mapping.py
        - requirements.txt
    - name: "H3D | Install requirements"
      pip:
        requirements: ~/.scripts/h3d/requirements.txt
        virtualenv: ~/.scripts/h3d
    - name: "H3D | Run h3d.py to run every hour 15 minutes"
      cron:
        name: "h3d"
        minute: "15"
        hour: "*"
        job: "~/.scripts/h3d/bin/python3 ~/.scripts/h3d/h3d.py"
  tags:
      - cron