---
- name: "Cron | Brew update every day at 12 noon"
  cron:
    name: "Brew Update"
    minute: "0"
    hour: "12"
    job: "brew update"
  tags: 
    - cron
    - brew
    - brew_update

- name: "Cron | Brew cleanup every 1st of the month at 12:30 noon"
  cron:
    name: "Brew Cleanup"
    minute: "30"
    hour: "12"
    day: "1"
    job: "brew cleanup --prune=all"
  tags: 
    - cron
    - brew
    - brew_cleanup

- name: "Pip | hurry.filesize"
  pip:
    name: hurry.filesize
    state: present
  become: true
  tags:
    - cron
    - pip
    - hurry_filesize
    
- name: "Cron | Ensure ~/.scripts folder exists"
  file:
    path: ~/.scripts
    state: directory

- name: "Cron | Setup Automate.py"
  block:
    - name: "Cron | Copy automate.py to scripts folder"
      copy:
        src: scripts/automate.py
        dest: ~/.scripts/automate.py

    - name: "Cron | Run automate.py to run every hour"
      cron:
        name: "Automate"
        minute: "0"
        hour: "*"
        job: "/opt/homebrew/bin/python3 ~/.scripts/automate.py >> /tmp/automate.log 2>&1"

    - name: "Cron | Setup logrotate for automate.log"
      block:
        - name: "Cron | Ensure logrotate is installed"
          homebrew:
            name: logrotate
            state: present

        - name: "Cron | Ensure logrotate.d folder exists"
          file:
            path: /opt/homebrew/etc/logrotate.d
            state: directory

        - name: "Cron | Create logrotate config for automate.log"
          file:
            path: /opt/homebrew/etc/logrotate.d/automate
            state: touch
        
        - name: "Cron | Add logrotate config for automate.log"
          blockinfile:
            path: /opt/homebrew/etc/logrotate.d/automate
            block: |
              /tmp/automate.log {
                maxsize 1M
                daily
                rotate 7
                compress
                delaycompress
                missingok
                notifempty
              }
  tags:
    - cron
    - automate_py

- name: "Cron | H3D"
  block:
    - name: "Cron | Copy h3d.py to scripts folder"
      copy:
        src: scripts/h3d.py
        dest: ~/.scripts/h3d.py
    - name: "Cron | Copy h3d_mapping.py to scripts folder"
      copy:
        src: scripts/h3d_mapping.py
        dest: ~/.scripts/h3d_mapping.py
    - name: "Cron | Run h3d.py to run every hour 15 minutes"
      cron:
        name: "h3d"
        minute: "15"
        hour: "*"
        job: "/opt/homebrew/bin/python3 ~/.scripts/h3d.py"