---
- name: "Cron | Brew update every day at 12 noon"
  cron:
    name: "Brew Update"
    minute: "0"
    hour: "12"
    job: "brew update"
  tags:
    - cron
    - brew
    - brew_update

- name: "Cron | Brew cleanup every 1st of the month at 12:30 noon"
  cron:
    name: "Brew Cleanup"
    minute: "30"
    hour: "12"
    day: "1"
    job: "brew cleanup --prune=all"
  tags:
    - cron
    - brew
    - brew_cleanup

- name: "Cron | Ensure VirtualEnv is installed"
  homebrew:
    name: virtualenv
    state: present
  tags:
    - cron

- name: "Cron | Setup NH Organizer"
  vars:
    current_install_dir: "~/.scripts/nh-organizer"
    repository: "{{ nho.repository }}"
  block:
    - name: "NHO | Ensure ~/.scripts folder exists"
      file:
        path: ~/.scripts
        state: directory
    - name: "NHO | Clone from repository"
      git:
        repo: "{{ repository }}"
        dest: "{{ current_install_dir }}"
    - name: "NHO | Install via Poetry"
      shell: "poetry install"
      args:
        chdir: "{{ current_install_dir }}"
    - name: "NHO | Write .env file"
      copy:
        dest: "{{ current_install_dir }}/.env"
        content: "{{ nho.env }}"
    - name: "NHO | Export requirements.txt"
      shell: "poetry export --without-hashes --format=requirements.txt > requirements.txt"
      args:
        chdir: "{{ current_install_dir }}"
    - name: "NHO | Install requirements"
      pip:
        requirements: "{{ current_install_dir }}/requirements.txt"
        virtualenv: "{{ current_install_dir }}"
    - name: "NHO | Run every hour"
      cron:
        name: "NHO"
        minute: "0"
        hour: "*"
        job: "{{ current_install_dir }}/bin/python3 {{ current_install_dir }}/main.py"
  tags:
    - cron

- name: "Cron | H3D"
  block:
    - name: "H3D | Ensure ~/.scripts/h3d folder exists"
      file:
        path: ~/.scripts/h3d
        state: directory
    - name: "H3D | Copy scripts"
      copy:
        src: scripts/h3d/{{ item }}
        dest: ~/.scripts/h3d/{{ item }}
      loop:
        - main.py
        - mapping.py
        - requirements.txt
    - name: "H3D | Install requirements"
      pip:
        requirements: ~/.scripts/h3d/requirements.txt
        virtualenv: ~/.scripts/h3d
    - name: "H3D | Run h3d.py to run every hour 15 minutes"
      cron:
        name: "h3d"
        minute: "15"
        hour: "*"
        job: "~/.scripts/h3d/bin/python3 ~/.scripts/h3d/main.py"
  tags:
    - cron
