---
- name: "System | Update Homebrew"
  community.general.homebrew:
    update_homebrew: true
  tags:
    - always
    - homebrew
    - homebrew_update

- name: "System | Install Homebrew Packages"
  community.general.homebrew:
    name:
      - curl
      - asdf
      - fzf
      - git
      - grep
      - btop
      - jq
      - yq
      - wget
      - yarn
      - zip
    state: present
  tags:
    - always
    - homebrew
    - homebrew_install
