---
- name: "Brew | Check if Brew is installed"
  shell: command -v brew
  register: result
  changed_when: false
  tags:
    - always
    - brew
    - brew_install

- set_fact:
    brew_installed: "{{ not result.failed | bool }}"
  tags:
    - always
    - brew

- name: "Brew | Install Brew"
  when: brew_installed == false
  shell: bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  tags:
    - always
    - brew
    - brew_install

# CRON Jobs
- name: "Brew | Install Brew Packages"
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ macos_brew_packages }}"
  tags:
    - always
    - brew
    - brew_install

- name: "Brew | Update every day at 12 noon"
  cron:
    name: "Brew Update"
    minute: "0"
    hour: "12"
    job: "brew update"
  tags:
    - brew
    - brew_update

- name: "Brew | Cleanup every 1st of the month at 12:30 noon"
  cron:
    name: "Brew Cleanup"
    minute: "30"
    hour: "12"
    day: "1"
    job: "brew cleanup --prune=all"
  tags:
    - brew
    - brew_cleanup

