---
- name: "tmux | Ensure tmux is installed"
  homebrew:
    name: "{{ item }}"
    state: "present"
  loop:
    - tmux
    - starship
    - tmuxinator
  tags:
    - tmux

- name: "tmux | Install TPM"
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
  tags:
    - tmux

- name: "tmux | Install xdg-utils"
  apt:
    name: "{{ item }}"
    state: "present"
  loop:
    - xdg-utils
  tags:
    - tmux

- name: "tmux | Install tmux configuration"
  copy:
    src: "files/tmux.conf"
    dest: "~/.tmux.conf"
  tags:
    - tmux

- name: "tmux | Install tmuxinator configuration"
  copy:
    src: files/tmuxinator/ubuntu/
    dest: "~/.config/tmuxinator/"
  tags:
    - tmux

- name: "tmux | Install starship toml"
  copy:
    src: files/starship.toml
    dest: "~/.config/starship.toml"
  tags:
    - tmux

- name: "tmux | Install tmuxinator completion"
  shell:
    cmd: fish -c "wget https://raw.githubusercontent.com/tmuxinator/tmuxinator/master/completion/tmuxinator.fish -O ~/.config/fish/completions/tmuxinator.fish"
  tags:
    - tmux
