---
- name: "Ensure tmux is installed"
  homebrew:
    name: "{{ item }}"
    state: "present"
  loop:
    - tmux
    - starship
    - tmuxinator
  tags:
    - tmux
    - tmuxinator
    - starship

- name: "Install TPM"
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
  tags:
    - tmux
    - tmuxinator
    - starship

- name: "Install xdg-utils"
  apt:
    name: "{{ item }}"
    state: "present"
  loop:
    - xdg-utils
  tags:
    - tmux
    - tmuxinator
    - starship

- name: "Install tmux configuration"
  copy:
    src: "files/tmux.conf"
    dest: "~/.tmux.conf"
  tags:
    - tmux
    - tmuxinator
    - starship

- name: "Install starship toml"
  copy:
    src: files/starship.toml
    dest: "~/.config/starship.toml"
  tags:
    - tmux
    - starship

- name: "tmuxinator setup"
  block:
    - name: "Install completion"
      shell:
        cmd: fish -c "wget https://raw.githubusercontent.com/tmuxinator/tmuxinator/master/completion/tmuxinator.fish -O ~/.config/fish/completions/tmuxinator.fish"

    - name: "Install configuration"
      copy:
        src: files/tmuxinator/ubuntu/
        dest: "~/.config/tmuxinator/"
  tags:
    - tmux
    - tmuxinator
