# dictionary on regex and destination folder
regex_dict = {
    r'ACIDIE': '[ACIDIE]',
    r'AkiyamaRyo': '[AkiyamaRyo]',
    r'AlenAbyss': '[AlenAbyss]',
    r'AliceCry': '[AliceCry]',
    r'Amelialtie': '[Amelialtie]',
    r'Amplected': '[Amplected]',
    r'Arhoangel': '[Arhoangel]',
    r'asayuki101': '[asayuki101]',
    r'Auxtasy': '[Auxtasy]',
    r'Bewyx': '[Bewyx]',
    r'BlueLightSFM': '[BlueLightSFM]',
    r'Bulging Senpai': '[Bulging Senpai]',
    r'BulgingS': '[Bulging Senpai]',
    r'BulgingSenpai': '[Bulging Senpai]',
    r'Derpixon': '[Derpixon]',
    r'DobermanS': '[DobermanS]',
    r'Echiee': '[Echiee]',
    r'Evilbaka': '[Evilbaka]',
    r'Exga': '[Exga]',
    r'Exprational': '[Exprational]',
    r'FPSBlyck': '[FPSBlyck]',
    r'Futuretist': '[Futuretist]',
    r'Giddora': '[Giddora]',
    r'Gifdoozer': '[Gifdoozer]',
    r'Grand Cupido': '[Grand Cupido]',
    r'Guiltyk': '[Guiltyk]',
    r'HydraFXX': '[HydraFXX]',
    r'Idemi-iam': '[Idemi-iam]',
    r'InitialA': '[InitialA]',
    r'juicyneko': '[juicyneko]',
    r'JuicyNeko': '[juicyneko]',
    r'kittyevil': '[Kittyyevil]',
    r'Kittyyevil': '[Kittyyevil]',
    r'LazyProcrast': '[LazyProcrast]',
    r'LazySoba': '[LazySoba]',
    r'Lewdgazer': '[Lewdgazer]',
    r'LitSilium': '[LitSilium]',
    r'lvl3toaster': '[lvl3toaster]',
    r'Lvl3Toaster': '[lvl3toaster]',
    r'Maiden Masher': '[MaidenMasher]',
    r'Maiden_Masher': '[MaidenMasher]',
    r'MaidenMasher': '[MaidenMasher]',
    r'MEGAERA': '[MEGAERA]',
    r'Mellewd': '[Mellewd]',
    r'Mokujin Hornywood': '[Mokujin Hornywood]',
    r'Mokujin_Hornywood': '[Mokujin Hornywood]',
    r'Mushiro': '[Mushiro]',
    r'Nagoonimation': '[Nagoonimation]',
    r'Noname55': '[Noname55]',
    r'PANGXXX': '[PANGXXX]',
    r'Pantsushi': '[Pantsushi]',
    r'Puuguy': '[Puuguy]',
    r'QoC': '[QoC]',
    r'RadiantEld': '[RadiantEld]',
    r'Rash Nemain': '[RashNemain]',
    r'RashNemain': '[RashNemain]',
    r'RedHot': '[RedHot]',
    r'Redmoa': '[Redmoa]',
    r'Rushzilla': '[Rushzilla]',
    r'SaveAss': '[SaveAss]',
    r'Secazz': '[Secazz]',
    r'SkRevenant': '[SkRevenant]',
    r'SleepyRandom': '[SleepyRandom]',
    r'spizder': '[spizder]',
    r'Spizzy': '[spizder]',
    r'stukove': '[stukove]',
    r'Suuru': '[Suuru]',
    r'TheAtKO': '[TheAtKO]',
    r'TheFastestGMan': '[TheFastestGMan]',
    r'ToonE': '[ToonE]',
    r'Topu': '[Topu]',
    r'VG Erotica': '[VG Erotica]',
    r'Vlese': '[Vlese]',
    r'Waifu Enjoyer': '[Waifu Enjoyer]',
    r'WaterRing': '[WaterRing]',
    r'Yeero': '[Yeero]',
}
