---
- name: "neovim | Ensure neovim is installed"
  homebrew:
    name: "neovim"
    state: "present"
  tags:
    - neovim

- name: "neovim | Check if lazyvim is installed"
  stat:
    path: "~/.config/nvimlazyvim.json"
  register: lazyvim_result
  tags:
    - neovim

- set_fact:
    lazyvim_installed: "{{ not lazyvim_result.failed | bool }}"
  tags:
    - neovim

- name: "neovim | Install lazygit"
  homebrew:
    name: "lazygit"
    state: "present"
  tags:
    - neovim

- name: "neovim | Install plugins"
  copy:
    src: "plugins/{{ item }}"
    dest: "~/.config/nvim/lua/plugins/{{ item }}"
  loop:
    - vim-tmux-navigator.lua
    - auto-session.lua
    - neo-tree.lua
  tags:
    - neovim
