---
- name: "neovim | Ensure neovim and its dependencies are installed"
  homebrew:
    name: "{{ item }}"
    state: "present"
  loop:
    - "neovim"
    - "bat"
    - "fzf"
    - "the_silver_searcher"
    - "ripgrep"
  tags:
    - neovim

- name: "neovim | Check if lazyvim is installed"
  stat:
    path: "~/.config/nvim/lazyvim.json"
  register: lazyvim_result
  tags:
    - neovim

- set_fact:
    lazyvim_installed: "{{ lazyvim_result.stat.exists | bool }}"
  tags:
    - neovim

- name: "neovim | Install LazyVim, if not installed"
  when: lazyvim_installed == false
  block:
    - name: "lazyvim | Cleanup nvim configs, caches, and states"
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "~/.config/nvim"
        - "~/.local/share/nvim"
        - "~/.local/state/nvim"
        - "~/.cache/nvim"
    - name: "lazyvim | Install LazyVim"
      git:
        repo: "https://github.com/LazyVim/starter"
        dest: "~/.config/nvim"
    - name: "lazyvim | Remove .git folder"
      file:
        path: "~/.config/nvim/.git"
        state: absent
  tags:
    - neovim
    - lazyvim

- name: "neovim | Install lazygit"
  homebrew:
    name: "lazygit"
    state: "present"
  tags:
    - neovim

- name: "neovim | Install plugins"
  copy:
    src: "plugins/{{ item }}"
    dest: "~/.config/nvim/lua/plugins/{{ item }}"
  loop:
    - vim-tmux-navigator.lua
    - auto-session.lua
    - neo-tree.lua
    - fzf.lua
    - catpuccin.lua
  tags:
    - neovim
